"""Adiciona Picture

Revision ID: d87018fca49d
Revises: e6b071d68095
Create Date: 2022-08-06 16:05:50.446099

"""

# pylint: skip-file

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd87018fca49d'
down_revision = 'e6b071d68095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('picture_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'user', 'picture', ['picture_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'picture_id')
    op.drop_table('picture')
    # ### end Alembic commands ###
